name: Finds twingos every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # This cron expression runs every 30 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Twingo requires a node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Twingo requires packages
        run: npm install

      # Run the script
      - name: Scraping twingos...
        run: node index.js

      # Save found twingos
      - name: Push found twingos in json file to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Pushing new twingos"
          commit_user_name: "GitHub Action"
          commit_user_email: "actions@github.com"