name: Finds twingos every 30 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # This cron expression runs every 30 minutes

jobs:
  find-twingos:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Twingo requires a node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Twingo requires packages
        run: npm install

      # Run the script
      - name: Scraping twingos...
        id: scraping-twingos
        run: |
          OUTPUT=$(node index.js)
          echo "SCRAPING_RESULT=$OUTPUT" >> $GITHUB_STATE
          echo "Scraping exited with with $OUTPUT"

      - name: Do this step when step with node index.js returns 1
        if: ${{ steps.scraping-twingos.outputs.SCRAPING_RESULT == '1' }}
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: New Twingos found!
          to: machacekmartin@icloud.com
          from: Twingo Finder
          html_body: file://twingos-email.html

      # Save found twingos
      - name: Push found twingos in json file to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Pushing new twingos"
          commit_user_name: "GitHub Action"
          commit_user_email: "actions@github.com"

